//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsSystem.EntityFramwork
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string FirstType { get; set; }
        public string SecondType { get; set; }
        public int CommentNumber { get; set; }
        public System.DateTime UpTime { get; set; }
        public string Writer { get; set; }
        public bool CheckImage { get; set; }
        public Nullable<bool> IsDelet { get; set; }
        public Nullable<bool> IsPublish { get; set; }
    }
}
