//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsSystem.EntityFramwork
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string UserAccout { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsDelet { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public string NickName { get; set; }
        public string Image { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> Brithday { get; set; }
        public string Address { get; set; }
        public string Autograph { get; set; }
    }
}
